// Braid protocol buffer definitions

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: braid.proto

package braid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageRef identifies a message by a versioned hash.
//
// Each field represents a distinct hashing scheme (fields included and
// algorithm used). Only one field should be set. Old schemes can be retired
// using 'reserved' or the 'deprecated' annotation.
type MessageRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sha256_v1: SHA-256 over the following fields of Message, using
	// explicit fixed-width big-endian encodings (not protobuf serialization):
	//
	//   - timestamp: int64 seconds || int32 nanos
	//   - author: ed25519_v1 public key bytes (32 bytes)
	//   - parent table: for each entry in order:
	//     parent sha256_v1 (32 bytes) || uint64 message_count
	//
	// The signature field is excluded.
	Sha256V1      []byte `protobuf:"bytes,1,opt,name=sha256_v1,json=sha256V1" json:"sha256_v1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRef) Reset() {
	*x = MessageRef{}
	mi := &file_braid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRef) ProtoMessage() {}

func (x *MessageRef) ProtoReflect() protoreflect.Message {
	mi := &file_braid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRef.ProtoReflect.Descriptor instead.
func (*MessageRef) Descriptor() ([]byte, []int) {
	return file_braid_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRef) GetSha256V1() []byte {
	if x != nil {
		return x.Sha256V1
	}
	return nil
}

// PublicKey identifies an author. Each field represents a distinct key
// algorithm. Only one field should be set.
type PublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ed25519V1     []byte                 `protobuf:"bytes,1,opt,name=ed25519_v1,json=ed25519V1" json:"ed25519_v1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_braid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_braid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_braid_proto_rawDescGZIP(), []int{1}
}

func (x *PublicKey) GetEd25519V1() []byte {
	if x != nil {
		return x.Ed25519V1
	}
	return nil
}

// Signature is a cryptographic signature over a message. Each field
// represents a distinct signing scheme. Only one field should be set.
type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ed25519V1     []byte                 `protobuf:"bytes,1,opt,name=ed25519_v1,json=ed25519V1" json:"ed25519_v1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_braid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_braid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_braid_proto_rawDescGZIP(), []int{2}
}

func (x *Signature) GetEd25519V1() []byte {
	if x != nil {
		return x.Ed25519V1
	}
	return nil
}

// ParentTable is an ordered list of parents and the count of additional
// messages reachable from each.
type ParentTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ParentTable_Entry   `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParentTable) Reset() {
	*x = ParentTable{}
	mi := &file_braid_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentTable) ProtoMessage() {}

func (x *ParentTable) ProtoReflect() protoreflect.Message {
	mi := &file_braid_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentTable.ProtoReflect.Descriptor instead.
func (*ParentTable) Descriptor() ([]byte, []int) {
	return file_braid_proto_rawDescGZIP(), []int{3}
}

func (x *ParentTable) GetEntries() []*ParentTable_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Message is a single entry in the hash chain.
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Parents       *ParentTable           `protobuf:"bytes,2,opt,name=parents" json:"parents,omitempty"`
	Author        *PublicKey             `protobuf:"bytes,3,opt,name=author" json:"author,omitempty"`
	Signature     *Signature             `protobuf:"bytes,4,opt,name=signature" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_braid_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_braid_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_braid_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Message) GetParents() *ParentTable {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *Message) GetAuthor() *PublicKey {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Message) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

// PeerInfo identifies a peer by its public key and listen address.
type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *PublicKey             `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Address       *string                `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_braid_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_braid_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_braid_proto_rawDescGZIP(), []int{5}
}

func (x *PeerInfo) GetKey() *PublicKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PeerInfo) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

// PeerGossip is a push-only list of known peers.
type PeerGossip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerGossip) Reset() {
	*x = PeerGossip{}
	mi := &file_braid_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerGossip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerGossip) ProtoMessage() {}

func (x *PeerGossip) ProtoReflect() protoreflect.Message {
	mi := &file_braid_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerGossip.ProtoReflect.Descriptor instead.
func (*PeerGossip) Descriptor() ([]byte, []int) {
	return file_braid_proto_rawDescGZIP(), []int{6}
}

func (x *PeerGossip) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

// ProbeRequest is sent to a peer to ask which of the sender's refs the
// peer has. The listed refs are the sender's current proposals (search
// cursors in the DAGdiff boundary-detection algorithm).
type ProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Have          []*MessageRef          `protobuf:"bytes,1,rep,name=have" json:"have,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	mi := &file_braid_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_braid_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_braid_proto_rawDescGZIP(), []int{7}
}

func (x *ProbeRequest) GetHave() []*MessageRef {
	if x != nil {
		return x.Have
	}
	return nil
}

// ProbeResponse answers a ProbeRequest. 'have' lists refs the responder
// already has; 'want' lists refs the responder is missing. Together they
// let the requester narrow the boundary between shared and unshared
// regions of the DAG.
type ProbeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Have          []*MessageRef          `protobuf:"bytes,1,rep,name=have" json:"have,omitempty"`
	Want          []*MessageRef          `protobuf:"bytes,2,rep,name=want" json:"want,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResponse) Reset() {
	*x = ProbeResponse{}
	mi := &file_braid_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResponse) ProtoMessage() {}

func (x *ProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_braid_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResponse.ProtoReflect.Descriptor instead.
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return file_braid_proto_rawDescGZIP(), []int{8}
}

func (x *ProbeResponse) GetHave() []*MessageRef {
	if x != nil {
		return x.Have
	}
	return nil
}

func (x *ProbeResponse) GetWant() []*MessageRef {
	if x != nil {
		return x.Want
	}
	return nil
}

// Envelope is the wire format for peer-to-peer communication.
// Each envelope is sent as a varint-encoded length prefix followed
// by the serialized Envelope bytes.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_Message
	//	*Envelope_PeerGossip
	//	*Envelope_ProbeRequest
	//	*Envelope_ProbeResponse
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_braid_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_braid_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_braid_proto_rawDescGZIP(), []int{9}
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *Envelope) GetPeerGossip() *PeerGossip {
	if x != nil {
		if x, ok := x.Body.(*Envelope_PeerGossip); ok {
			return x.PeerGossip
		}
	}
	return nil
}

func (x *Envelope) GetProbeRequest() *ProbeRequest {
	if x != nil {
		if x, ok := x.Body.(*Envelope_ProbeRequest); ok {
			return x.ProbeRequest
		}
	}
	return nil
}

func (x *Envelope) GetProbeResponse() *ProbeResponse {
	if x != nil {
		if x, ok := x.Body.(*Envelope_ProbeResponse); ok {
			return x.ProbeResponse
		}
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_Message struct {
	Message *Message `protobuf:"bytes,1,opt,name=message,oneof"`
}

type Envelope_PeerGossip struct {
	PeerGossip *PeerGossip `protobuf:"bytes,2,opt,name=peer_gossip,json=peerGossip,oneof"`
}

type Envelope_ProbeRequest struct {
	ProbeRequest *ProbeRequest `protobuf:"bytes,3,opt,name=probe_request,json=probeRequest,oneof"`
}

type Envelope_ProbeResponse struct {
	ProbeResponse *ProbeResponse `protobuf:"bytes,4,opt,name=probe_response,json=probeResponse,oneof"`
}

func (*Envelope_Message) isEnvelope_Body() {}

func (*Envelope_PeerGossip) isEnvelope_Body() {}

func (*Envelope_ProbeRequest) isEnvelope_Body() {}

func (*Envelope_ProbeResponse) isEnvelope_Body() {}

type ParentTable_Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        *MessageRef            `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	MessageCount  *uint64                `protobuf:"varint,2,opt,name=message_count,json=messageCount" json:"message_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParentTable_Entry) Reset() {
	*x = ParentTable_Entry{}
	mi := &file_braid_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentTable_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentTable_Entry) ProtoMessage() {}

func (x *ParentTable_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_braid_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentTable_Entry.ProtoReflect.Descriptor instead.
func (*ParentTable_Entry) Descriptor() ([]byte, []int) {
	return file_braid_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ParentTable_Entry) GetParent() *MessageRef {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *ParentTable_Entry) GetMessageCount() uint64 {
	if x != nil && x.MessageCount != nil {
		return *x.MessageCount
	}
	return 0
}

var File_braid_proto protoreflect.FileDescriptor

const file_braid_proto_rawDesc = "" +
	"\n" +
	"\vbraid.proto\x12\x05braid\x1a\x1fgoogle/protobuf/timestamp.proto\")\n" +
	"\n" +
	"MessageRef\x12\x1b\n" +
	"\tsha256_v1\x18\x01 \x01(\fR\bsha256V1\"*\n" +
	"\tPublicKey\x12\x1d\n" +
	"\n" +
	"ed25519_v1\x18\x01 \x01(\fR\ted25519V1\"*\n" +
	"\tSignature\x12\x1d\n" +
	"\n" +
	"ed25519_v1\x18\x01 \x01(\fR\ted25519V1\"\x9a\x01\n" +
	"\vParentTable\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.braid.ParentTable.EntryR\aentries\x1aW\n" +
	"\x05Entry\x12)\n" +
	"\x06parent\x18\x01 \x01(\v2\x11.braid.MessageRefR\x06parent\x12#\n" +
	"\rmessage_count\x18\x02 \x01(\x04R\fmessageCount\"\xcb\x01\n" +
	"\aMessage\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12,\n" +
	"\aparents\x18\x02 \x01(\v2\x12.braid.ParentTableR\aparents\x12(\n" +
	"\x06author\x18\x03 \x01(\v2\x10.braid.PublicKeyR\x06author\x12.\n" +
	"\tsignature\x18\x04 \x01(\v2\x10.braid.SignatureR\tsignature\"H\n" +
	"\bPeerInfo\x12\"\n" +
	"\x03key\x18\x01 \x01(\v2\x10.braid.PublicKeyR\x03key\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"3\n" +
	"\n" +
	"PeerGossip\x12%\n" +
	"\x05peers\x18\x01 \x03(\v2\x0f.braid.PeerInfoR\x05peers\"5\n" +
	"\fProbeRequest\x12%\n" +
	"\x04have\x18\x01 \x03(\v2\x11.braid.MessageRefR\x04have\"]\n" +
	"\rProbeResponse\x12%\n" +
	"\x04have\x18\x01 \x03(\v2\x11.braid.MessageRefR\x04have\x12%\n" +
	"\x04want\x18\x02 \x03(\v2\x11.braid.MessageRefR\x04want\"\xef\x01\n" +
	"\bEnvelope\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x0e.braid.MessageH\x00R\amessage\x124\n" +
	"\vpeer_gossip\x18\x02 \x01(\v2\x11.braid.PeerGossipH\x00R\n" +
	"peerGossip\x12:\n" +
	"\rprobe_request\x18\x03 \x01(\v2\x13.braid.ProbeRequestH\x00R\fprobeRequest\x12=\n" +
	"\x0eprobe_response\x18\x04 \x01(\v2\x14.braid.ProbeResponseH\x00R\rprobeResponseB\x06\n" +
	"\x04bodyB\x1aZ\x18github.com/vsekhar/braidb\beditionsp\xe8\a"

var (
	file_braid_proto_rawDescOnce sync.Once
	file_braid_proto_rawDescData []byte
)

func file_braid_proto_rawDescGZIP() []byte {
	file_braid_proto_rawDescOnce.Do(func() {
		file_braid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_braid_proto_rawDesc), len(file_braid_proto_rawDesc)))
	})
	return file_braid_proto_rawDescData
}

var file_braid_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_braid_proto_goTypes = []any{
	(*MessageRef)(nil),            // 0: braid.MessageRef
	(*PublicKey)(nil),             // 1: braid.PublicKey
	(*Signature)(nil),             // 2: braid.Signature
	(*ParentTable)(nil),           // 3: braid.ParentTable
	(*Message)(nil),               // 4: braid.Message
	(*PeerInfo)(nil),              // 5: braid.PeerInfo
	(*PeerGossip)(nil),            // 6: braid.PeerGossip
	(*ProbeRequest)(nil),          // 7: braid.ProbeRequest
	(*ProbeResponse)(nil),         // 8: braid.ProbeResponse
	(*Envelope)(nil),              // 9: braid.Envelope
	(*ParentTable_Entry)(nil),     // 10: braid.ParentTable.Entry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_braid_proto_depIdxs = []int32{
	10, // 0: braid.ParentTable.entries:type_name -> braid.ParentTable.Entry
	11, // 1: braid.Message.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 2: braid.Message.parents:type_name -> braid.ParentTable
	1,  // 3: braid.Message.author:type_name -> braid.PublicKey
	2,  // 4: braid.Message.signature:type_name -> braid.Signature
	1,  // 5: braid.PeerInfo.key:type_name -> braid.PublicKey
	5,  // 6: braid.PeerGossip.peers:type_name -> braid.PeerInfo
	0,  // 7: braid.ProbeRequest.have:type_name -> braid.MessageRef
	0,  // 8: braid.ProbeResponse.have:type_name -> braid.MessageRef
	0,  // 9: braid.ProbeResponse.want:type_name -> braid.MessageRef
	4,  // 10: braid.Envelope.message:type_name -> braid.Message
	6,  // 11: braid.Envelope.peer_gossip:type_name -> braid.PeerGossip
	7,  // 12: braid.Envelope.probe_request:type_name -> braid.ProbeRequest
	8,  // 13: braid.Envelope.probe_response:type_name -> braid.ProbeResponse
	0,  // 14: braid.ParentTable.Entry.parent:type_name -> braid.MessageRef
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_braid_proto_init() }
func file_braid_proto_init() {
	if File_braid_proto != nil {
		return
	}
	file_braid_proto_msgTypes[9].OneofWrappers = []any{
		(*Envelope_Message)(nil),
		(*Envelope_PeerGossip)(nil),
		(*Envelope_ProbeRequest)(nil),
		(*Envelope_ProbeResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_braid_proto_rawDesc), len(file_braid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_braid_proto_goTypes,
		DependencyIndexes: file_braid_proto_depIdxs,
		MessageInfos:      file_braid_proto_msgTypes,
	}.Build()
	File_braid_proto = out.File
	file_braid_proto_goTypes = nil
	file_braid_proto_depIdxs = nil
}
