// Braid protocol buffer definitions

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: braid.proto

package braid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageRef identifies a message by a versioned hash.
//
// Each field represents a distinct hashing scheme (fields included and
// algorithm used). Only one field should be set. Old schemes can be retired
// using 'reserved' or the 'deprecated' annotation.
type MessageRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256V1      []byte                 `protobuf:"bytes,1,opt,name=sha256_v1,json=sha256V1" json:"sha256_v1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRef) Reset() {
	*x = MessageRef{}
	mi := &file_braid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRef) ProtoMessage() {}

func (x *MessageRef) ProtoReflect() protoreflect.Message {
	mi := &file_braid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRef.ProtoReflect.Descriptor instead.
func (*MessageRef) Descriptor() ([]byte, []int) {
	return file_braid_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRef) GetSha256V1() []byte {
	if x != nil {
		return x.Sha256V1
	}
	return nil
}

// PublicKey identifies an author. Each field represents a distinct key
// algorithm. Only one field should be set.
type PublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ed25519V1     []byte                 `protobuf:"bytes,1,opt,name=ed25519_v1,json=ed25519V1" json:"ed25519_v1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_braid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_braid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_braid_proto_rawDescGZIP(), []int{1}
}

func (x *PublicKey) GetEd25519V1() []byte {
	if x != nil {
		return x.Ed25519V1
	}
	return nil
}

// Signature is a cryptographic signature over a message. Each field
// represents a distinct signing scheme. Only one field should be set.
type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ed25519V1     []byte                 `protobuf:"bytes,1,opt,name=ed25519_v1,json=ed25519V1" json:"ed25519_v1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_braid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_braid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_braid_proto_rawDescGZIP(), []int{2}
}

func (x *Signature) GetEd25519V1() []byte {
	if x != nil {
		return x.Ed25519V1
	}
	return nil
}

// ParentTable is an ordered list of parents and the count of additional
// messages reachable from each.
type ParentTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ParentTable_Entry   `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParentTable) Reset() {
	*x = ParentTable{}
	mi := &file_braid_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentTable) ProtoMessage() {}

func (x *ParentTable) ProtoReflect() protoreflect.Message {
	mi := &file_braid_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentTable.ProtoReflect.Descriptor instead.
func (*ParentTable) Descriptor() ([]byte, []int) {
	return file_braid_proto_rawDescGZIP(), []int{3}
}

func (x *ParentTable) GetEntries() []*ParentTable_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Message is a single entry in the hash chain.
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Parents       *ParentTable           `protobuf:"bytes,2,opt,name=parents" json:"parents,omitempty"`
	Author        *PublicKey             `protobuf:"bytes,3,opt,name=author" json:"author,omitempty"`
	Signature     *Signature             `protobuf:"bytes,4,opt,name=signature" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_braid_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_braid_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_braid_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Message) GetParents() *ParentTable {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *Message) GetAuthor() *PublicKey {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Message) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ParentTable_Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        *MessageRef            `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	MessageCount  *uint64                `protobuf:"varint,2,opt,name=message_count,json=messageCount" json:"message_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParentTable_Entry) Reset() {
	*x = ParentTable_Entry{}
	mi := &file_braid_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentTable_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentTable_Entry) ProtoMessage() {}

func (x *ParentTable_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_braid_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentTable_Entry.ProtoReflect.Descriptor instead.
func (*ParentTable_Entry) Descriptor() ([]byte, []int) {
	return file_braid_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ParentTable_Entry) GetParent() *MessageRef {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *ParentTable_Entry) GetMessageCount() uint64 {
	if x != nil && x.MessageCount != nil {
		return *x.MessageCount
	}
	return 0
}

var File_braid_proto protoreflect.FileDescriptor

const file_braid_proto_rawDesc = "" +
	"\n" +
	"\vbraid.proto\x12\x05braid\x1a\x1fgoogle/protobuf/timestamp.proto\")\n" +
	"\n" +
	"MessageRef\x12\x1b\n" +
	"\tsha256_v1\x18\x01 \x01(\fR\bsha256V1\"*\n" +
	"\tPublicKey\x12\x1d\n" +
	"\n" +
	"ed25519_v1\x18\x01 \x01(\fR\ted25519V1\"*\n" +
	"\tSignature\x12\x1d\n" +
	"\n" +
	"ed25519_v1\x18\x01 \x01(\fR\ted25519V1\"\x9a\x01\n" +
	"\vParentTable\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.braid.ParentTable.EntryR\aentries\x1aW\n" +
	"\x05Entry\x12)\n" +
	"\x06parent\x18\x01 \x01(\v2\x11.braid.MessageRefR\x06parent\x12#\n" +
	"\rmessage_count\x18\x02 \x01(\x04R\fmessageCount\"\xcb\x01\n" +
	"\aMessage\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12,\n" +
	"\aparents\x18\x02 \x01(\v2\x12.braid.ParentTableR\aparents\x12(\n" +
	"\x06author\x18\x03 \x01(\v2\x10.braid.PublicKeyR\x06author\x12.\n" +
	"\tsignature\x18\x04 \x01(\v2\x10.braid.SignatureR\tsignatureB\x1aZ\x18github.com/vsekhar/braidb\beditionsp\xe8\a"

var (
	file_braid_proto_rawDescOnce sync.Once
	file_braid_proto_rawDescData []byte
)

func file_braid_proto_rawDescGZIP() []byte {
	file_braid_proto_rawDescOnce.Do(func() {
		file_braid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_braid_proto_rawDesc), len(file_braid_proto_rawDesc)))
	})
	return file_braid_proto_rawDescData
}

var file_braid_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_braid_proto_goTypes = []any{
	(*MessageRef)(nil),            // 0: braid.MessageRef
	(*PublicKey)(nil),             // 1: braid.PublicKey
	(*Signature)(nil),             // 2: braid.Signature
	(*ParentTable)(nil),           // 3: braid.ParentTable
	(*Message)(nil),               // 4: braid.Message
	(*ParentTable_Entry)(nil),     // 5: braid.ParentTable.Entry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_braid_proto_depIdxs = []int32{
	5, // 0: braid.ParentTable.entries:type_name -> braid.ParentTable.Entry
	6, // 1: braid.Message.timestamp:type_name -> google.protobuf.Timestamp
	3, // 2: braid.Message.parents:type_name -> braid.ParentTable
	1, // 3: braid.Message.author:type_name -> braid.PublicKey
	2, // 4: braid.Message.signature:type_name -> braid.Signature
	0, // 5: braid.ParentTable.Entry.parent:type_name -> braid.MessageRef
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_braid_proto_init() }
func file_braid_proto_init() {
	if File_braid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_braid_proto_rawDesc), len(file_braid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_braid_proto_goTypes,
		DependencyIndexes: file_braid_proto_depIdxs,
		MessageInfos:      file_braid_proto_msgTypes,
	}.Build()
	File_braid_proto = out.File
	file_braid_proto_goTypes = nil
	file_braid_proto_depIdxs = nil
}
