// Extended Envelope definition for testing unknown field detection.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/testproto/extended.proto

package testproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FutureMessage is a message type that does not exist in the current proto.
type FutureMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *string                `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FutureMessage) Reset() {
	*x = FutureMessage{}
	mi := &file_internal_testproto_extended_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FutureMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FutureMessage) ProtoMessage() {}

func (x *FutureMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_extended_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FutureMessage.ProtoReflect.Descriptor instead.
func (*FutureMessage) Descriptor() ([]byte, []int) {
	return file_internal_testproto_extended_proto_rawDescGZIP(), []int{0}
}

func (x *FutureMessage) GetPayload() string {
	if x != nil && x.Payload != nil {
		return *x.Payload
	}
	return ""
}

// ExtendedEnvelope mirrors braid.Envelope but adds an additional oneof variant
// with a high field number to avoid collisions with future Envelope fields.
type ExtendedEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ExtendedEnvelope_Message
	//	*ExtendedEnvelope_PeerGossip
	//	*ExtendedEnvelope_ProbeRequest
	//	*ExtendedEnvelope_ProbeResponse
	//	*ExtendedEnvelope_Future
	Body          isExtendedEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendedEnvelope) Reset() {
	*x = ExtendedEnvelope{}
	mi := &file_internal_testproto_extended_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendedEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendedEnvelope) ProtoMessage() {}

func (x *ExtendedEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_extended_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendedEnvelope.ProtoReflect.Descriptor instead.
func (*ExtendedEnvelope) Descriptor() ([]byte, []int) {
	return file_internal_testproto_extended_proto_rawDescGZIP(), []int{1}
}

func (x *ExtendedEnvelope) GetBody() isExtendedEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ExtendedEnvelope) GetMessage() []byte {
	if x != nil {
		if x, ok := x.Body.(*ExtendedEnvelope_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ExtendedEnvelope) GetPeerGossip() []byte {
	if x != nil {
		if x, ok := x.Body.(*ExtendedEnvelope_PeerGossip); ok {
			return x.PeerGossip
		}
	}
	return nil
}

func (x *ExtendedEnvelope) GetProbeRequest() []byte {
	if x != nil {
		if x, ok := x.Body.(*ExtendedEnvelope_ProbeRequest); ok {
			return x.ProbeRequest
		}
	}
	return nil
}

func (x *ExtendedEnvelope) GetProbeResponse() []byte {
	if x != nil {
		if x, ok := x.Body.(*ExtendedEnvelope_ProbeResponse); ok {
			return x.ProbeResponse
		}
	}
	return nil
}

func (x *ExtendedEnvelope) GetFuture() *FutureMessage {
	if x != nil {
		if x, ok := x.Body.(*ExtendedEnvelope_Future); ok {
			return x.Future
		}
	}
	return nil
}

type isExtendedEnvelope_Body interface {
	isExtendedEnvelope_Body()
}

type ExtendedEnvelope_Message struct {
	Message []byte `protobuf:"bytes,1,opt,name=message,oneof"`
}

type ExtendedEnvelope_PeerGossip struct {
	PeerGossip []byte `protobuf:"bytes,2,opt,name=peer_gossip,json=peerGossip,oneof"`
}

type ExtendedEnvelope_ProbeRequest struct {
	ProbeRequest []byte `protobuf:"bytes,3,opt,name=probe_request,json=probeRequest,oneof"`
}

type ExtendedEnvelope_ProbeResponse struct {
	ProbeResponse []byte `protobuf:"bytes,4,opt,name=probe_response,json=probeResponse,oneof"`
}

type ExtendedEnvelope_Future struct {
	Future *FutureMessage `protobuf:"bytes,100,opt,name=future,oneof"`
}

func (*ExtendedEnvelope_Message) isExtendedEnvelope_Body() {}

func (*ExtendedEnvelope_PeerGossip) isExtendedEnvelope_Body() {}

func (*ExtendedEnvelope_ProbeRequest) isExtendedEnvelope_Body() {}

func (*ExtendedEnvelope_ProbeResponse) isExtendedEnvelope_Body() {}

func (*ExtendedEnvelope_Future) isExtendedEnvelope_Body() {}

var File_internal_testproto_extended_proto protoreflect.FileDescriptor

const file_internal_testproto_extended_proto_rawDesc = "" +
	"\n" +
	"!internal/testproto/extended.proto\x12\ttestproto\")\n" +
	"\rFutureMessage\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\"\xdd\x01\n" +
	"\x10ExtendedEnvelope\x12\x1a\n" +
	"\amessage\x18\x01 \x01(\fH\x00R\amessage\x12!\n" +
	"\vpeer_gossip\x18\x02 \x01(\fH\x00R\n" +
	"peerGossip\x12%\n" +
	"\rprobe_request\x18\x03 \x01(\fH\x00R\fprobeRequest\x12'\n" +
	"\x0eprobe_response\x18\x04 \x01(\fH\x00R\rprobeResponse\x122\n" +
	"\x06future\x18d \x01(\v2\x18.testproto.FutureMessageH\x00R\x06futureB\x06\n" +
	"\x04bodyB-Z+github.com/vsekhar/braid/internal/testprotob\beditionsp\xe8\a"

var (
	file_internal_testproto_extended_proto_rawDescOnce sync.Once
	file_internal_testproto_extended_proto_rawDescData []byte
)

func file_internal_testproto_extended_proto_rawDescGZIP() []byte {
	file_internal_testproto_extended_proto_rawDescOnce.Do(func() {
		file_internal_testproto_extended_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_testproto_extended_proto_rawDesc), len(file_internal_testproto_extended_proto_rawDesc)))
	})
	return file_internal_testproto_extended_proto_rawDescData
}

var file_internal_testproto_extended_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_testproto_extended_proto_goTypes = []any{
	(*FutureMessage)(nil),    // 0: testproto.FutureMessage
	(*ExtendedEnvelope)(nil), // 1: testproto.ExtendedEnvelope
}
var file_internal_testproto_extended_proto_depIdxs = []int32{
	0, // 0: testproto.ExtendedEnvelope.future:type_name -> testproto.FutureMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_testproto_extended_proto_init() }
func file_internal_testproto_extended_proto_init() {
	if File_internal_testproto_extended_proto != nil {
		return
	}
	file_internal_testproto_extended_proto_msgTypes[1].OneofWrappers = []any{
		(*ExtendedEnvelope_Message)(nil),
		(*ExtendedEnvelope_PeerGossip)(nil),
		(*ExtendedEnvelope_ProbeRequest)(nil),
		(*ExtendedEnvelope_ProbeResponse)(nil),
		(*ExtendedEnvelope_Future)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_testproto_extended_proto_rawDesc), len(file_internal_testproto_extended_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_testproto_extended_proto_goTypes,
		DependencyIndexes: file_internal_testproto_extended_proto_depIdxs,
		MessageInfos:      file_internal_testproto_extended_proto_msgTypes,
	}.Build()
	File_internal_testproto_extended_proto = out.File
	file_internal_testproto_extended_proto_goTypes = nil
	file_internal_testproto_extended_proto_depIdxs = nil
}
