// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: frame.proto

package braidpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Frame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*Frame_Noop
	//	*Frame_Message
	//	*Frame_RequestMessages
	//	*Frame_Peer
	//	*Frame_RequestPeers
	//	*Frame_LastField
	Payload isFrame_Payload `protobuf_oneof:"payload"`
}

func (x *Frame) Reset() {
	*x = Frame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frame_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_frame_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_frame_proto_rawDescGZIP(), []int{0}
}

func (m *Frame) GetPayload() isFrame_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Frame) GetNoop() *NoOp {
	if x, ok := x.GetPayload().(*Frame_Noop); ok {
		return x.Noop
	}
	return nil
}

func (x *Frame) GetMessage() *Message {
	if x, ok := x.GetPayload().(*Frame_Message); ok {
		return x.Message
	}
	return nil
}

func (x *Frame) GetRequestMessages() *RequestMessages {
	if x, ok := x.GetPayload().(*Frame_RequestMessages); ok {
		return x.RequestMessages
	}
	return nil
}

func (x *Frame) GetPeer() *Peer {
	if x, ok := x.GetPayload().(*Frame_Peer); ok {
		return x.Peer
	}
	return nil
}

func (x *Frame) GetRequestPeers() *RequestPeers {
	if x, ok := x.GetPayload().(*Frame_RequestPeers); ok {
		return x.RequestPeers
	}
	return nil
}

func (x *Frame) GetLastField() *NoOp {
	if x, ok := x.GetPayload().(*Frame_LastField); ok {
		return x.LastField
	}
	return nil
}

type isFrame_Payload interface {
	isFrame_Payload()
}

type Frame_Noop struct {
	Noop *NoOp `protobuf:"bytes,1,opt,name=noop,proto3,oneof"`
}

type Frame_Message struct {
	Message *Message `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
}

type Frame_RequestMessages struct {
	RequestMessages *RequestMessages `protobuf:"bytes,3,opt,name=request_messages,json=requestMessages,proto3,oneof"`
}

type Frame_Peer struct {
	Peer *Peer `protobuf:"bytes,4,opt,name=peer,proto3,oneof"`
}

type Frame_RequestPeers struct {
	RequestPeers *RequestPeers `protobuf:"bytes,5,opt,name=request_peers,json=requestPeers,proto3,oneof"`
}

type Frame_LastField struct {
	LastField *NoOp `protobuf:"bytes,536870911,opt,name=lastField,proto3,oneof"` // for testing
}

func (*Frame_Noop) isFrame_Payload() {}

func (*Frame_Message) isFrame_Payload() {}

func (*Frame_RequestMessages) isFrame_Payload() {}

func (*Frame_Peer) isFrame_Payload() {}

func (*Frame_RequestPeers) isFrame_Payload() {}

func (*Frame_LastField) isFrame_Payload() {}

type NoOp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoOp) Reset() {
	*x = NoOp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frame_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoOp) ProtoMessage() {}

func (x *NoOp) ProtoReflect() protoreflect.Message {
	mi := &file_frame_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoOp.ProtoReflect.Descriptor instead.
func (*NoOp) Descriptor() ([]byte, []int) {
	return file_frame_proto_rawDescGZIP(), []int{1}
}

var File_frame_proto protoreflect.FileDescriptor

var file_frame_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62,
	0x72, 0x61, 0x69, 0x64, 0x1a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb6, 0x02, 0x0a, 0x05, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x6e, 0x6f, 0x6f,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x64, 0x2e,
	0x4e, 0x6f, 0x4f, 0x70, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x6f, 0x6f, 0x70, 0x12, 0x2a, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x62, 0x72, 0x61, 0x69, 0x64, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x43, 0x0a, 0x10, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x21, 0x0a,
	0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x72,
	0x61, 0x69, 0x64, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x48, 0x00, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72,
	0x12, 0x3a, 0x0a, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x65, 0x65, 0x72,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x64, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x48, 0x00, 0x52, 0x0c,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x12, 0x2f, 0x0a, 0x09,
	0x6c, 0x61, 0x73, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0xff, 0xff, 0xff, 0xff, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x64, 0x2e, 0x4e, 0x6f, 0x4f, 0x70,
	0x48, 0x00, 0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x09, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x06, 0x0a, 0x04, 0x4e, 0x6f, 0x4f, 0x70,
	0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76,
	0x73, 0x65, 0x6b, 0x68, 0x61, 0x72, 0x2f, 0x62, 0x72, 0x61, 0x69, 0x64, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x72, 0x61, 0x69, 0x64, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_frame_proto_rawDescOnce sync.Once
	file_frame_proto_rawDescData = file_frame_proto_rawDesc
)

func file_frame_proto_rawDescGZIP() []byte {
	file_frame_proto_rawDescOnce.Do(func() {
		file_frame_proto_rawDescData = protoimpl.X.CompressGZIP(file_frame_proto_rawDescData)
	})
	return file_frame_proto_rawDescData
}

var file_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_frame_proto_goTypes = []interface{}{
	(*Frame)(nil),           // 0: braid.Frame
	(*NoOp)(nil),            // 1: braid.NoOp
	(*Message)(nil),         // 2: braid.Message
	(*RequestMessages)(nil), // 3: braid.RequestMessages
	(*Peer)(nil),            // 4: braid.Peer
	(*RequestPeers)(nil),    // 5: braid.RequestPeers
}
var file_frame_proto_depIdxs = []int32{
	1, // 0: braid.Frame.noop:type_name -> braid.NoOp
	2, // 1: braid.Frame.message:type_name -> braid.Message
	3, // 2: braid.Frame.request_messages:type_name -> braid.RequestMessages
	4, // 3: braid.Frame.peer:type_name -> braid.Peer
	5, // 4: braid.Frame.request_peers:type_name -> braid.RequestPeers
	1, // 5: braid.Frame.lastField:type_name -> braid.NoOp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_frame_proto_init() }
func file_frame_proto_init() {
	if File_frame_proto != nil {
		return
	}
	file_message_proto_init()
	file_peer_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_frame_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Frame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frame_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoOp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_frame_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Frame_Noop)(nil),
		(*Frame_Message)(nil),
		(*Frame_RequestMessages)(nil),
		(*Frame_Peer)(nil),
		(*Frame_RequestPeers)(nil),
		(*Frame_LastField)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_frame_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frame_proto_goTypes,
		DependencyIndexes: file_frame_proto_depIdxs,
		MessageInfos:      file_frame_proto_msgTypes,
	}.Build()
	File_frame_proto = out.File
	file_frame_proto_rawDesc = nil
	file_frame_proto_goTypes = nil
	file_frame_proto_depIdxs = nil
}
